### PR TITLE
Fix setup so it doesn't pull in Qiskit and remove outdated code

### PR DESCRIPTION
**Pull request by jwoehr**
QISKitError -> QiskitError
Remove unused import

### CODE REVIEW

**Comment by jwoehr** [comment]
Please let me know if this code has been abandoned :)

It needs more work. It doesn't actually run anymore.

**Comment by adamisntdead** [comment]
Not abandoned! I will update today

**Comment by jwoehr** [comment]
BTW [nice paper](https://arxiv.org/pdf/1805.00988.pdf) :)

**Comment by adamisntdead** [comment]
Hello! Thanks for the PR, this is now fixed! It works now, so should be updating the QCGPU upstream, and then releasing the new PyPI version of this package.

**Pull request closed without merging**
